begin;
create extension if not exists pgtap with schema extensions;
select plan(17);
select policies_are('public','swipes',array['swipes_own_delete','swipes_own_insert','swipes_own_read','swipes_own_update'],'Swipes expose only own-row policies');
select policies_are('public','matches',array['matches_owner_archive','matches_read'],'Matches cannot be directly inserted');
select policies_are('public','notifications',array['notifications_delete','notifications_read','notifications_update'],'Notifications cannot be directly inserted');
select policies_are('public','invitations',array[]::text[],'Invitations cannot be directly queried');
select has_function('private','create_love_match',array[]::name[],'Match trigger exists');
select function_is_security_definer('private','create_love_match',array[]::name[],'Match trigger is definer');
select has_trigger('public','swipes','love_match','Swipe match trigger attached');
select col_is_unique('public','matches',array['group_id','listing_id'],'Duplicate match prevented');
select col_is_unique('public','notifications',array['user_id','match_id','type'],'Duplicate notification prevented');
select has_check('public','search_groups','Group size has constraint');
select has_trigger('public','group_members','max_two_members','Third active member rejected');
select has_function('private','accept_invite',array['text','uuid'],'Atomic invitation accept exists');
select function_is_security_definer('private','accept_invite',array['text','uuid'],'Invitation accept is definer');
select has_trigger('auth','users','auth_user_profile','Profiles auto-created');
select has_trigger('public','search_groups','group_owner','Owner membership auto-created');
select has_index('public','invitations','invitations_token_hash_key','Invitation hashes indexed uniquely');
select tables_are('public',array['group_listings','group_members','invitations','matches','notifications','profiles','search_groups','swipes'],'All Phase 2 tables exist');
select * from finish(); rollback;
