import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { ListingImage } from "../components/ListingImage";
import { useConnectedRepository } from "../listings/useConnectedRepository";
import { currency, number } from "../lib/format";
import type { DecisionKind, Listing } from "../types/models";

export function ConnectedListingDetailsPage() {
  const { groupId = "", listingId = "" } = useParams(), repository = useConnectedRepository();
  const [listing, setListing] = useState<Listing>(), [decided, setDecided] = useState(false), [error, setError] = useState("");
  useEffect(() => { if (!repository) return; let active = true; Promise.all([repository.getCachedInventory(groupId), repository.getMySwipes(groupId)]).then(([inventory, swipes]) => { if (!active) return; setListing(inventory.listings.find(item => item.id === decodeURIComponent(listingId))); setDecided(swipes.some(item => item.listingId === decodeURIComponent(listingId))); }).catch(() => active && setError("We could not load this listing.")); return () => { active = false; }; }, [groupId, listingId, repository]);
  const decide = async (choice: DecisionKind) => { if (!repository || !listing) return; try { await repository.saveSwipe(groupId, listing.id, choice); setDecided(true); } catch { setError("Your private choice was not saved."); } };
  if (!listing) return <section className="page empty"><h1>{error || "Loading listing…"}</h1><Link className="button" to={`/groups/${groupId}/discover`}>Back to swipe deck</Link></section>;
  const facts = [["Bedrooms", listing.bedrooms], ["Bathrooms", listing.bathrooms], ["Square feet", listing.squareFeet === undefined ? undefined : number(listing.squareFeet)], ["Year built", listing.yearBuilt], ["Property type", listing.propertyType], ["Days on market", listing.daysOnMarket]].filter((item) => item[1] !== undefined);
  const images = listing.photoUrls.length || listing.imageUrls?.length || 1;
  return <section className="page detail"><Link className="text-link" to={`/groups/${groupId}/discover`}>← Back to swipe deck</Link><div className="detail-grid"><div className="listing-gallery">{Array.from({ length: images }, (_, index) => <ListingImage listing={listing} index={index} key={index} />)}</div><div><p className="eyebrow">Active listing data</p><h1>{currency(listing.price)}</h1><h2>{listing.formattedAddress ?? `${listing.addressLine1}, ${listing.city}, ${listing.state} ${listing.zipCode}`}</h2><div className="detail-facts">{facts.map(([label, value]) => <div key={String(label)}><span>{label}</span><b>{value}</b></div>)}</div>{listing.description && <><h2>About this home</h2><p>{listing.description}</p></>}{(listing.listingAgentName || listing.listingOfficeName) && <p><strong>Listing attribution:</strong> {[listing.listingAgentName, listing.listingOfficeName].filter(Boolean).join(" · ")}</p>}{error && <p role="alert" className="form-error">{error}</p>}{!decided && <div className="decisions detail-actions"><button onClick={() => void decide("pass")} aria-label="Pass on this home">× Pass</button><button onClick={() => void decide("maybe")} aria-label="Save this home as maybe">◇ Maybe</button><button onClick={() => void decide("love")} aria-label="Love this home">♡ Love</button></div>}{listing.providerUrl && <a className="button secondary" href={listing.providerUrl} target="_blank" rel="noopener noreferrer">Open original listing</a>}<p className="provider-disclaimer">Listing information may change. Verify availability and details with a licensed real-estate professional.</p></div></div></section>;
}
