import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { ListingImage } from "../components/ListingImage";
import { useConnectedRepository } from "../listings/useConnectedRepository";
import { useAuth } from "../auth/AuthProvider";
import { currency, number } from "../lib/format";
import type { DecisionKind, Listing } from "../types/models";
import type { HouseMatch, MatchNote } from "../collaboration/types";

export function ConnectedListingDetailsPage() {
  const { groupId = "", listingId = "" } = useParams(), repository = useConnectedRepository(), { user } = useAuth(), id = decodeURIComponent(listingId);
  const [listing, setListing] = useState<Listing>(), [decision, setDecision] = useState<DecisionKind>(), [match, setMatch] = useState<HouseMatch>(), [notes, setNotes] = useState<MatchNote[]>([]), [body, setBody] = useState(""), [saving, setSaving] = useState(false), [error, setError] = useState("");
  const load = async () => { if (!repository) return; try { const [inventory, swipes, matches] = await Promise.all([repository.getCachedInventory!(groupId), repository.getMySwipes(groupId), repository.getMatches(groupId, true)]); const found = matches.find(item => item.listingId === id); setListing(inventory.listings.find(item => item.id === id)); setDecision(swipes.find(item => item.listingId === id)?.decision); setMatch(found); if (found && repository.getMatchNotes) setNotes(await repository.getMatchNotes(found.id)); } catch { setError("We could not load this listing. Check your connection and access."); } };
  useEffect(() => { void load(); }, [groupId, id, repository]);
  const decide = async (choice: DecisionKind) => { if (!repository || !listing || saving) return; setSaving(true); setError(""); try { await repository.saveSwipe(groupId, listing.id, choice); setDecision(choice); await load(); } catch { setError("We could not save that choice. Try again."); } finally { setSaving(false); } };
  const addNote = async () => { if (!repository?.createMatchNote || !match || saving) return; const clean=body.trim(); if(!clean||clean.length>1000){setError("Enter a note of 1,000 characters or fewer.");return} setSaving(true); try { await repository.createMatchNote(match.id,groupId,clean);setBody("");await load(); } catch { setError("We could not save that note. Try again."); } finally { setSaving(false); } };
  const removeNote=async(note:MatchNote)=>{if(!repository?.deleteMatchNote)return;try{await repository.deleteMatchNote(note.id);await load()}catch{setError("We could not delete that note.")}};
  if (!listing) return <section className="page empty"><h1>{error || "Loading listing…"}</h1><Link className="button" to={`/groups/${groupId}`}>Back to shared search</Link></section>;
  const facts = [["Bedrooms", listing.bedrooms], ["Bathrooms", listing.bathrooms], ["Square feet", listing.squareFeet === undefined ? undefined : number(listing.squareFeet)], ["Year built", listing.yearBuilt], ["Property type", listing.propertyType], ["Days on market", listing.daysOnMarket]].filter((item) => item[1] !== undefined), images = listing.photoUrls.length || listing.imageUrls?.length || 1;
  const state=match?(match.archived?"Archived House Match":"Mutual House Match"):decision?`Your choice: ${decision[0].toUpperCase()}${decision.slice(1)}`:"Not reviewed";
  return <section className="page detail"><Link className="text-link" to={match?`/groups/${groupId}/matches`:`/groups/${groupId}/discover`}>← Back to {match?"matches":"review"}</Link><div className="detail-grid"><div className="listing-gallery">{Array.from({ length: images }, (_, index) => <ListingImage listing={listing} index={index} key={index} />)}</div><div><p className="eyebrow">{state}</p><h1>{currency(listing.price)}</h1><h2>{listing.formattedAddress ?? `${listing.addressLine1}, ${listing.city}, ${listing.state} ${listing.zipCode}`}</h2><div className="detail-facts">{facts.map(([label, value]) => <div key={String(label)}><span>{label}</span><b>{value}</b></div>)}</div>{listing.description && <><h2>About this home</h2><p>{listing.description}</p></>}{error && <p role="alert" className="form-error">{error}</p>}<div className="decisions detail-actions" aria-label="Change your private choice"><button disabled={saving} aria-pressed={decision==="pass"} onClick={() => void decide("pass")}>× Pass</button><button disabled={saving} aria-pressed={decision==="maybe"} onClick={() => void decide("maybe")}>◇ Maybe</button><button disabled={saving} aria-pressed={decision==="love"} onClick={() => void decide("love")}>♡ Love</button></div>{match&&<section className="notes"><h2>Shared notes</h2>{match.archived&&<p>This match is archived, so new notes are disabled.</p>}{!notes.length&&<p>No notes yet. What do we want to remember about this home?</p>}{notes.map(note=><article key={note.id}><p>{note.body}</p><small>{note.authorName} · {new Date(note.createdAt).toLocaleString()}</small>{note.authorId===user?.id&&<button className="text-link" onClick={()=>void removeNote(note)}>Delete</button>}</article>)}{!match.archived&&<><label htmlFor="note-body">Add a shared note</label><textarea id="note-body" maxLength={1000} rows={3} value={body} onChange={e=>setBody(e.target.value)} placeholder="Ask about the roof. Love the kitchen…"/><div className="title-row"><small>{body.length}/1000</small><button disabled={saving||!body.trim()} onClick={()=>void addNote()}>Save note</button></div></>}<Link className="button secondary" to={`/groups/${groupId}/compare?listingIds=${listing.id}`}>Select from Matches to compare</Link></section>}{listing.providerUrl && <a className="button secondary" href={listing.providerUrl} target="_blank" rel="noopener noreferrer">Open original listing</a>}<p className="provider-disclaimer">Listing information may change. Verify availability and details with a licensed real-estate professional.</p></div></div></section>;
}
