import { useEffect, useState, type FormEvent } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { useConnectedRepository } from "../listings/useConnectedRepository";
import type { ListingSearchRequest } from "../listings/listingTypes";
import { dateTime } from "../lib/format";
import { CollaborationError } from "../collaboration/SupabaseCollaborationRepository";

export const validateLocation = (mode: "city" | "zip", city: string, state: string, zip: string) => mode === "city"
  ? city.trim().length > 0 && city.trim().length <= 80 && /^[A-Z]{2}$/.test(state)
  : /^\d{5}$/.test(zip);

export function GroupSearchPage() {
  const { groupId = "" } = useParams(), repository = useConnectedRepository(), navigate = useNavigate();
  const [mode, setMode] = useState<"city" | "zip">("city"), [city, setCity] = useState(""), [state, setState] = useState(""), [zip, setZip] = useState("");
  const [minPrice, setMinPrice] = useState(""), [maxPrice, setMaxPrice] = useState(""), [beds, setBeds] = useState(""), [baths, setBaths] = useState("");
  const [types, setTypes] = useState<string[]>([]), [count, setCount] = useState(0), [fetchedAt, setFetchedAt] = useState<string>(), [isOwner, setIsOwner] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState("");
  useEffect(() => { if (!repository) return; let active = true; void Promise.all([repository.getGroup(groupId), repository.getCachedInventory(groupId)]).then(([group, inventory]) => { if (!active) return; setMode(group.criteria.mode); setCity(group.criteria.city); setState(group.criteria.state); setZip(group.criteria.zipCode); setMinPrice(group.criteria.minPrice?.toString() ?? ""); setMaxPrice(group.criteria.maxPrice?.toString() ?? ""); setBeds(group.criteria.minBedrooms?.toString() ?? ""); setBaths(group.criteria.minBathrooms?.toString() ?? ""); setTypes(group.criteria.propertyTypes); setIsOwner(group.currentUserRole === "owner"); setCount(inventory.listings.length); setFetchedAt(inventory.fetchedAt); }).catch(() => active && setError("We could not load this shared search.")); return () => { active = false; }; }, [groupId, repository]);
  const number = (value: string) => value === "" ? undefined : Number(value);
  const submit = async (event: FormEvent, refresh: boolean) => { event.preventDefault(); if (busy || !repository?.searchListings) return; setError("");
    if (!isOwner) { setError("You must be the group owner to refresh listings."); return; }
    if (!validateLocation(mode, city, state, zip)) { setError(mode === "city" ? "Enter a city and a two-letter uppercase state." : "Enter a five-digit ZIP code."); return; }
    if (number(minPrice)! < 0 || number(maxPrice)! < 0 || (number(minPrice) !== undefined && number(maxPrice) !== undefined && number(minPrice)! > number(maxPrice)!)) { setError("Enter a valid price range."); return; }
    if (refresh && count > 0 && !window.confirm("Refresh the group’s listing set? Existing swipes and matches will be preserved.")) return;
    setBusy(true); try { const location: ListingSearchRequest["location"] = mode === "city" ? { type: "city", city: city.trim(), state } : { type: "zip", zipCode: zip }; const result = await repository.searchListings({ groupId, location, criteria: { minPrice: number(minPrice), maxPrice: number(maxPrice), minBedrooms: number(beds), minBathrooms: number(baths), propertyTypes: types }, refresh }); setCount(result.total); setFetchedAt(result.fetchedAt); if (!result.total) { setError("No active listings were found. Try broadening your criteria."); return; } navigate(`/groups/${groupId}`, { replace: true }); } catch (reason) { const code = reason instanceof CollaborationError ? reason.code : "unavailable"; setError({ not_configured: "Listings service is not configured.", invalid: "Search criteria are invalid.", session: "Your session expired. Sign in again.", owner: "You must be the group owner to refresh listings.", database_setup: "NestMatch’s shared-search database setup is incomplete.", unavailable: "The listing provider is temporarily unavailable. Please try again." }[code]); } finally { setBusy(false); }
  };
  const choices = ["Single-family", "Condo", "Townhouse", "Multi-family", "Manufactured"];
  return <section className="page narrow search-setup"><p className="eyebrow">Active listing data</p><h1>Find homes for your shared search</h1><p>Listings are requested only when the owner taps a button, then cached for both group members.</p><form onSubmit={(event) => void submit(event, count > 0)} noValidate><fieldset><legend>Location</legend><label><input type="radio" checked={mode === "city"} onChange={() => setMode("city")} /> City and state</label><label><input type="radio" checked={mode === "zip"} onChange={() => setMode("zip")} /> ZIP code</label></fieldset>{mode === "city" ? <div className="form-grid"><label>City<input value={city} onChange={e => setCity(e.target.value)} placeholder="Cincinnati" maxLength={80} /></label><label>State<input value={state} onChange={e => setState(e.target.value.toUpperCase())} placeholder="OH" maxLength={2} /></label></div> : <label>ZIP code<input inputMode="numeric" value={zip} onChange={e => setZip(e.target.value)} placeholder="45245" maxLength={5} /></label>}<div className="form-grid"><label>Minimum price<input type="number" min="0" value={minPrice} onChange={e => setMinPrice(e.target.value)} /></label><label>Maximum price<input type="number" min="0" value={maxPrice} onChange={e => setMaxPrice(e.target.value)} /></label><label>Minimum bedrooms<input type="number" min="0" max="20" value={beds} onChange={e => setBeds(e.target.value)} /></label><label>Minimum bathrooms<input type="number" min="0" max="20" step="0.5" value={baths} onChange={e => setBaths(e.target.value)} /></label></div><fieldset><legend>Property types</legend>{choices.map(choice => <label key={choice}><input type="checkbox" checked={types.includes(choice)} onChange={e => setTypes(old => e.target.checked ? [...old, choice] : old.filter(item => item !== choice))} /> {choice}</label>)}</fieldset>{!isOwner && <p className="status-warning">Only the group owner can edit criteria or refresh listings.</p>}{error && <p className="form-error" role="alert">{error}</p>}{isOwner && <button className="button primary" disabled={busy}>{busy ? "Finding active homes…" : count ? "Refresh active homes" : "Find active homes"}</button>}</form><div className="source-box" aria-live="polite"><strong>{count} saved {count === 1 ? "home" : "homes"}</strong><p>{fetchedAt ? `Last refreshed ${dateTime(fetchedAt)}` : "Not refreshed yet"}</p></div><Link className="button secondary" to={count ? `/groups/${groupId}/discover` : `/groups/${groupId}`}>{count ? "Open listing deck" : "Back to search dashboard"}</Link><p className="provider-disclaimer">Listing information may change. Verify availability and details with a licensed real-estate professional.</p></section>;
}
