import { useCallback, useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { useConnectedRepository } from "../listings/useConnectedRepository";
import { useGroupRealtime } from "../listings/useGroupRealtime";
import type { SearchGroupDetail } from "../collaboration/types";
import type { CachedListingInventory } from "../listings/listingTypes";
import { InvitePartnerCard } from "../components/collaboration/InvitePartnerCard";

export function GroupDashboardPage() {
  const { groupId = "" } = useParams(), repository = useConnectedRepository();
  const [group, setGroup] = useState<SearchGroupDetail>(), [inventory, setInventory] = useState<CachedListingInventory>(), [stats, setStats] = useState({ reviewed: 0, maybes: 0, matches: 0 }), [error, setError] = useState(""), [loading, setLoading] = useState(true);
  const [inviteToken, setInviteToken] = useState(""), [inviteBusy, setInviteBusy] = useState(false), [inviteError, setInviteError] = useState("");
  const load = useCallback(() => { if (!repository) return; Promise.all([repository.getGroup(groupId), repository.getCachedInventory!(groupId), repository.getMySwipes(groupId), repository.getMatches(groupId)]).then(([detail, cached, swipes, matches]) => { setGroup(detail); setInventory(cached); setStats({ reviewed: swipes.length, maybes: swipes.filter(s => s.decision === "maybe").length, matches: matches.length }); setError(""); }).catch(() => setError("We could not open this shared search. Check your access and try again.")).finally(() => setLoading(false)); }, [groupId, repository]);
  useEffect(load, [load]); const realtime = useGroupRealtime(groupId, load);
  const createInvite = async () => { if (!repository || inviteBusy) return; setInviteBusy(true); setInviteError(""); try { const result = await repository.createInvitation(groupId); setInviteToken(result.token); } catch { setInviteError("We could not create an invitation. Please try again."); } finally { setInviteBusy(false); } };
  const revokeInvite = async () => { if (!repository) return; try { await repository.revokeInvitation(groupId); setInviteToken(""); } catch { setInviteError("We could not revoke that invitation."); } };
  const replaceInvite = async () => { if (!repository) return; try { await repository.revokeInvitation(groupId); setInviteToken(""); const result = await repository.createInvitation(groupId); setInviteToken(result.token); } catch { setInviteError("We could not replace that invitation."); } };
  if (loading) return <section className="page empty"><h1>Loading your shared search…</h1></section>;
  if (!group || !inventory) return <section className="page empty"><h1>Search unavailable</h1><p role="alert">{error}</p><Link className="button" to="/groups">My searches</Link></section>;
  const remaining = Math.max(0, inventory.listings.length - stats.reviewed), criteria = group.criteria;
  return <section className="page group-home"><div className="hero compact"><p className="eyebrow">Shared home search</p><h1>{group.name}</h1><p>Signed in as <strong>{group.currentUserName}</strong> · {group.memberCount === 2 ? `Searching with ${group.partnerName}` : "Waiting for your person"}</p></div>{!realtime && <p className="status-warning">Live updates are reconnecting. This page refreshes automatically every 30 seconds.</p>}{group.memberCount === 1 && group.currentUserRole === "owner" && <div className="privacy-card"><div><h2>Your search is ready</h2><p>You may begin reviewing now. House Matches appear only after your person joins and independently Loves the same home.</p>{!inviteToken && <button className="button primary" disabled={inviteBusy} onClick={() => void createInvite()}>{inviteBusy ? "Creating invitation…" : "Invite your person"}</button>}{inviteError && <p className="form-error" role="alert">{inviteError}</p>}</div></div>}{inviteToken && <InvitePartnerCard token={inviteToken} onRevoke={revokeInvite} onReplace={replaceInvite} />}<div className="stats-grid"><article><b>{inventory.listings.length}</b><span>Cached homes</span></article><article><b>{stats.reviewed}</b><span>You reviewed</span></article><article><b>{remaining}</b><span>Remaining for you</span></article><article><b>{stats.maybes}</b><span>Your Maybes</span></article><article><b>{stats.matches}</b><span>House Matches</span></article></div><div className="privacy-card"><h2>Search criteria</h2><p>{criteria.mode === "zip" ? criteria.zipCode : `${criteria.city}, ${criteria.state}`} · Up to ${new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(criteria.maxPrice)} · {criteria.minBedrooms}+ beds · {criteria.minBathrooms}+ baths</p><p><strong>Source:</strong> {inventory.listings[0]?.sourceLabel ?? "RentCast"} · <strong>Last refreshed:</strong> {inventory.fetchedAt ? new Date(inventory.fetchedAt).toLocaleString() : "Not yet refreshed"}</p></div><div className="group-actions">{inventory.listings.length ? <Link className="button primary" to={`/groups/${groupId}/discover`}>{remaining ? "Continue reviewing homes" : "Review complete"}</Link> : <Link className="button primary" to={`/groups/${groupId}/search`}>Find homes</Link>}<Link className="button" to={`/groups/${groupId}/maybes`}>View my Maybes</Link><Link className="button" to={`/groups/${groupId}/matches`}>View our matches</Link>{group.currentUserRole === "owner" && <Link className="button secondary" to={`/groups/${groupId}/search`}>Edit search</Link>}</div></section>;
}
