import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { useApp } from "../app/AppContext";
import { useAuth } from "../auth/AuthProvider";
import { useCollaboration } from "../collaboration/CollaborationContext";
import { useConnectedRepository } from "../listings/useConnectedRepository";
import type { UserNotification } from "../collaboration/types";
import type { Listing } from "../types/models";
export function NotificationsPage() { const app=useApp(),demo=useCollaboration(),auth=useAuth(),repository=useConnectedRepository(),[connected,setConnected]=useState<UserNotification[]>([]),[listings,setListings]=useState(new Map<string,Listing>()),[error,setError]=useState(""); const load=async()=>{if(!repository)return;try{const notifications=await repository.getNotifications();setConnected(notifications);const groups=[...new Set(notifications.map(n=>n.groupId))];const inventories=await Promise.all(groups.map(g=>repository.getCachedInventory!(g)));setListings(new Map(inventories.flatMap(i=>i.listings).map(l=>[l.id,l])))}catch{setError("We could not load notifications.")}};useEffect(()=>{void load()},[repository]);const notifications=auth.user?connected:demo.notifications;const mark=async(id:string)=>{if(repository&&auth.user){await repository.markNotificationRead(id);await load()}else await demo.markRead(id)};return <section className="page narrow"><h1>Notifications</h1><p>{notifications.filter(n=>!n.readAt).length} unread</p>{error&&<p role="alert">{error}</p>}{!notifications.length?<div className="empty"><h2>You’re all caught up</h2><p>New House Matches will appear here.</p></div>:<div className="notification-list">{notifications.map(n=>{const listing=auth.user?listings.get(n.listingId):app.result.listings.find(l=>l.id===n.listingId);const path=auth.user?`/groups/${n.groupId}/listings/${encodeURIComponent(n.listingId)}`:"/group/demo/matches";return <article className={n.readAt?"":"unread"} key={n.id}><div><strong>New House Match</strong><p>{listing?.formattedAddress??listing?.addressLine1??"Matched home"} · {new Date(n.createdAt).toLocaleString()}</p></div><Link to={path} onClick={()=>void mark(n.id)}>Open match</Link>{!n.readAt&&<button className="text-link undo" onClick={()=>void mark(n.id)}>Mark read</button>}</article>})}</div>}</section> }
