import type { SupabaseClient } from "@supabase/supabase-js";
import type { Criteria, DecisionKind, Listing } from "../types/models";
import type { CollaborationRepository, CreateGroupInput, HouseMatch, SearchGroup, SearchGroupDetail, SwipeResult, UserNotification, UserSwipe } from "./types";
import type { CreateInvitationResponse, InvitationResponse } from "../types/database.types";

const safeObject = (value: unknown): value is Record<string, unknown> => !!value && typeof value === "object" && !Array.isArray(value);
async function invoke<T>(client: SupabaseClient, name: string, body: Record<string, string>): Promise<T> { const { data, error } = await client.functions.invoke(name, { body }); if (error || !safeObject(data)) throw new Error("The secure request could not be completed."); return data as T; }
export class SupabaseCollaborationRepository implements CollaborationRepository {
  constructor(private readonly client: SupabaseClient, private readonly userId: string) {}
  async listGroups(): Promise<SearchGroup[]> { const { data, error } = await this.client.from("search_groups").select("id,name").eq("status", "active"); if (error) throw error; return (data ?? []).map((row: Record<string, unknown>) => ({ id: row.id, name: row.name, partnerName: "Partner" })); }
  async createGroup(input: CreateGroupInput): Promise<SearchGroup> { const { data, error } = await this.client.from("search_groups").insert({ owner_id: this.userId, name: input.name?.trim() || "Our Home Search", criteria: input.criteria }).select("id,name").single(); if (error) throw error; return { ...data, partnerName: "Waiting for partner" }; }
  async getGroup(groupId: string): Promise<SearchGroupDetail> { const { data, error } = await this.client.from("search_groups").select("id,name,criteria").eq("id", groupId).single(); if (error || !safeObject(data.criteria)) throw new Error("Search unavailable"); return { id: data.id, name: data.name, partnerName: "Partner", criteria: data.criteria as unknown as Criteria }; }
  async updateCriteria(groupId: string, criteria: Criteria) { const { error } = await this.client.from("search_groups").update({ criteria }).eq("id", groupId); if (error) throw error; }
  async getGroupListings(groupId: string): Promise<Listing[]> { const { data, error } = await this.client.from("group_listings").select("listing_snapshot").eq("group_id", groupId); if (error) throw error; return (data ?? []).flatMap((row: Record<string, unknown>) => safeObject(row.listing_snapshot) && typeof row.listing_snapshot.id === "string" ? [row.listing_snapshot as unknown as Listing] : []); }
  async saveSwipe(groupId: string, listingId: string, decision: DecisionKind): Promise<SwipeResult> { const { data, error } = await this.client.from("swipes").upsert({ group_id: groupId, listing_id: listingId, user_id: this.userId, decision }).select("listing_id,decision,updated_at").single(); if (error) throw error; return { swipe: { listingId: data.listing_id, decision: data.decision, savedAt: data.updated_at } }; }
  async removeSwipe(groupId: string, listingId: string) { const { error } = await this.client.from("swipes").delete().eq("group_id", groupId).eq("listing_id", listingId).eq("user_id", this.userId); if (error) throw error; return true; }
  async getMySwipes(groupId: string): Promise<UserSwipe[]> { const { data, error } = await this.client.from("swipes").select("listing_id,decision,updated_at").eq("group_id", groupId).eq("user_id", this.userId); if (error) throw error; return (data ?? []).map((row: Record<string, unknown>) => ({ listingId: row.listing_id, decision: row.decision, savedAt: row.updated_at })); }
  async getMatches(groupId: string): Promise<HouseMatch[]> { const { data, error } = await this.client.from("matches").select("id,group_id,listing_id,created_at,status").eq("group_id", groupId).eq("status", "active"); if (error) throw error; return (data ?? []).map((row: Record<string, unknown>) => ({ id: row.id, groupId: row.group_id, listingId: row.listing_id, createdAt: row.created_at, archived: false })); }
  async getNotifications(): Promise<UserNotification[]> { const { data, error } = await this.client.from("notifications").select("id,group_id,match_id,created_at,read_at,matches(listing_id)").eq("user_id", this.userId); if (error) throw error; return (data ?? []).map((row: Record<string, unknown>) => ({ id: row.id, groupId: row.group_id, matchId: row.match_id, listingId: (row.matches as { listing_id?: string } | null)?.listing_id ?? "", createdAt: row.created_at, readAt: row.read_at ?? undefined })); }
  async markNotificationRead(id: string) { const { error } = await this.client.from("notifications").update({ read_at: new Date().toISOString() }).eq("id", id).eq("user_id", this.userId); if (error) throw error; }
  async archiveMatch(id: string) { const { error } = await this.client.from("matches").update({ status: "archived" }).eq("id", id); if (error) throw error; }
  async reset() { /* Connected data is never erased by the demo reset. */ }
  createInvitation(groupId: string) { return invoke<CreateInvitationResponse>(this.client, "create-invite", { groupId }); }
  acceptInvitation(token: string) { return invoke<InvitationResponse>(this.client, "accept-invite", { token }); }
  revokeInvitation(groupId: string) { return invoke<{ revoked: boolean }>(this.client, "revoke-invite", { groupId }); }
}
