-- Phase 2 secure collaboration foundation. Browser access is constrained by RLS.
create extension if not exists pgcrypto;
create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

do $$ begin create type public.group_status as enum ('active','archived'); exception when duplicate_object then null; end $$;
do $$ begin create type public.member_role as enum ('owner','member'); exception when duplicate_object then null; end $$;
do $$ begin create type public.member_status as enum ('active','left','removed'); exception when duplicate_object then null; end $$;
do $$ begin create type public.swipe_decision as enum ('pass','maybe','love'); exception when duplicate_object then null; end $$;
do $$ begin create type public.match_status as enum ('active','archived'); exception when duplicate_object then null; end $$;

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text not null default '' check (display_name = '' or btrim(display_name) <> ''), avatar_color text, browser_notifications_enabled boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.search_groups (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id), name text not null check (btrim(name)<>''), criteria jsonb not null check (jsonb_typeof(criteria)='object'), status public.group_status not null default 'active', max_members integer not null default 2 check(max_members=2), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.group_members (group_id uuid not null references public.search_groups(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, role public.member_role not null, status public.member_status not null default 'active', joined_at timestamptz not null default now(), left_at timestamptz, primary key(group_id,user_id));
create table public.group_listings (group_id uuid not null references public.search_groups(id) on delete cascade, listing_id text not null check(btrim(listing_id)<>''), listing_snapshot jsonb not null check(jsonb_typeof(listing_snapshot)='object'), source text not null check(btrim(source)<>''), fetched_at timestamptz not null default now(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), primary key(group_id,listing_id));
create table public.swipes (group_id uuid not null references public.search_groups(id) on delete cascade, listing_id text not null, user_id uuid not null references auth.users(id) on delete cascade, decision public.swipe_decision not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), primary key(group_id,listing_id,user_id), foreign key(group_id,listing_id) references public.group_listings(group_id,listing_id) on delete cascade);
create table public.matches (id uuid primary key default gen_random_uuid(), group_id uuid not null references public.search_groups(id) on delete cascade, listing_id text not null, match_type text not null default 'love_love' check(match_type='love_love'), status public.match_status not null default 'active', created_at timestamptz not null default now(), unique(group_id,listing_id), foreign key(group_id,listing_id) references public.group_listings(group_id,listing_id) on delete cascade);
create table public.notifications (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, group_id uuid not null references public.search_groups(id) on delete cascade, match_id uuid references public.matches(id) on delete cascade, type text not null check(type='house_match'), read_at timestamptz, created_at timestamptz not null default now(), unique(user_id,match_id,type));
create table public.invitations (id uuid primary key default gen_random_uuid(), group_id uuid not null references public.search_groups(id) on delete cascade, created_by uuid not null references auth.users(id) on delete cascade, token_hash text not null unique check(token_hash ~ '^[0-9a-f]{64}$'), expires_at timestamptz not null default(now()+interval '7 days'), accepted_by uuid references auth.users(id), accepted_at timestamptz, revoked_at timestamptz, created_at timestamptz not null default now());

create index group_members_user_idx on public.group_members(user_id); create index group_members_active_idx on public.group_members(group_id,status) where status='active'; create index group_listings_group_idx on public.group_listings(group_id); create index swipes_match_idx on public.swipes(group_id,listing_id,decision); create index swipes_user_idx on public.swipes(user_id); create index matches_group_idx on public.matches(group_id); create index notifications_unread_idx on public.notifications(user_id,read_at); create index invitations_group_idx on public.invitations(group_id); -- token_hash unique constraint supplies its index.

create function private.set_updated_at() returns trigger language plpgsql security definer set search_path='' as $$ begin new.updated_at=now(); return new; end $$;
create trigger profiles_updated before update on public.profiles for each row execute function private.set_updated_at(); create trigger groups_updated before update on public.search_groups for each row execute function private.set_updated_at(); create trigger listings_updated before update on public.group_listings for each row execute function private.set_updated_at(); create trigger swipes_updated before update on public.swipes for each row execute function private.set_updated_at();
create function private.new_profile() returns trigger language plpgsql security definer set search_path='' as $$ begin insert into public.profiles(id,display_name) values(new.id,'') on conflict do nothing; return new; end $$;
create trigger auth_user_profile after insert on auth.users for each row execute function private.new_profile();
create function private.add_group_owner() returns trigger language plpgsql security definer set search_path='' as $$ begin insert into public.group_members(group_id,user_id,role) values(new.id,new.owner_id,'owner'); return new; end $$;
create trigger group_owner after insert on public.search_groups for each row execute function private.add_group_owner();
create function private.enforce_two_members() returns trigger language plpgsql security definer set search_path='' as $$ begin if new.status='active' and (select count(*) from public.group_members where group_id=new.group_id and status='active' and user_id<>new.user_id)>=2 then raise exception 'group_full' using errcode='23514'; end if; return new; end $$;
create trigger max_two_members before insert or update of status on public.group_members for each row execute function private.enforce_two_members();

create function private.is_group_member(g uuid) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.group_members where group_id=g and user_id=auth.uid() and status='active') $$;
create function private.is_group_owner(g uuid) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.group_members where group_id=g and user_id=auth.uid() and role='owner' and status='active') $$;
create function private.shares_group_with(other uuid) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.group_members me join public.group_members them using(group_id) where me.user_id=auth.uid() and them.user_id=other and me.status='active' and them.status='active') $$;
grant usage on schema private to authenticated; grant execute on function private.is_group_member(uuid),private.is_group_owner(uuid),private.shares_group_with(uuid) to authenticated;

-- SECURITY BOUNDARY: partner identity and decisions are resolved from memberships server-side.
create function private.create_love_match() returns trigger language plpgsql security definer set search_path='' as $$ declare other_id uuid; new_match uuid; begin if new.decision<>'love' then return new; end if; if not exists(select 1 from public.group_members where group_id=new.group_id and user_id=new.user_id and status='active') then raise exception 'not_active_member'; end if; select user_id into other_id from public.group_members where group_id=new.group_id and user_id<>new.user_id and status='active' limit 1; if other_id is null or not exists(select 1 from public.swipes where group_id=new.group_id and listing_id=new.listing_id and user_id=other_id and decision='love') then return new; end if; insert into public.matches(group_id,listing_id) values(new.group_id,new.listing_id) on conflict do nothing returning id into new_match; if new_match is not null then insert into public.notifications(user_id,group_id,match_id,type) select user_id,new.group_id,new_match,'house_match' from public.group_members where group_id=new.group_id and status='active' on conflict do nothing; end if; return new; end $$;
create trigger love_match after insert or update of decision on public.swipes for each row execute function private.create_love_match();

alter table public.profiles enable row level security; alter table public.search_groups enable row level security; alter table public.group_members enable row level security; alter table public.group_listings enable row level security; alter table public.swipes enable row level security; alter table public.matches enable row level security; alter table public.notifications enable row level security; alter table public.invitations enable row level security;
create policy profile_read on public.profiles for select to authenticated using(id=auth.uid() or private.shares_group_with(id)); create policy profile_update on public.profiles for update to authenticated using(id=auth.uid()) with check(id=auth.uid());
create policy groups_read on public.search_groups for select to authenticated using(private.is_group_member(id)); create policy groups_create on public.search_groups for insert to authenticated with check(owner_id=auth.uid()); create policy groups_update on public.search_groups for update to authenticated using(private.is_group_owner(id)) with check(owner_id=auth.uid());
create policy members_read on public.group_members for select to authenticated using(private.is_group_member(group_id)); create policy members_leave on public.group_members for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid() and status='left');
create policy listings_read on public.group_listings for select to authenticated using(private.is_group_member(group_id)); create policy listings_insert on public.group_listings for insert to authenticated with check(private.is_group_owner(group_id)); create policy listings_update on public.group_listings for update to authenticated using(private.is_group_owner(group_id)) with check(private.is_group_owner(group_id)); create policy listings_delete on public.group_listings for delete to authenticated using(private.is_group_owner(group_id));
create policy swipes_own_read on public.swipes for select to authenticated using(user_id=auth.uid() and private.is_group_member(group_id)); create policy swipes_own_insert on public.swipes for insert to authenticated with check(user_id=auth.uid() and private.is_group_member(group_id)); create policy swipes_own_update on public.swipes for update to authenticated using(user_id=auth.uid() and private.is_group_member(group_id)) with check(user_id=auth.uid() and private.is_group_member(group_id)); create policy swipes_own_delete on public.swipes for delete to authenticated using(user_id=auth.uid() and private.is_group_member(group_id));
create policy matches_read on public.matches for select to authenticated using(private.is_group_member(group_id)); create policy matches_owner_archive on public.matches for update to authenticated using(private.is_group_owner(group_id)) with check(private.is_group_owner(group_id));
create policy notifications_read on public.notifications for select to authenticated using(user_id=auth.uid()); create policy notifications_update on public.notifications for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid()); create policy notifications_delete on public.notifications for delete to authenticated using(user_id=auth.uid());
-- Invitations intentionally have no policies: Edge Functions are the only API boundary.

-- Atomic service-only invitation acceptance. Edge Functions verify JWTs and call these with service role.
create function private.accept_invite(hash text, accepting_user uuid) returns uuid language plpgsql security definer set search_path='' as $$ declare inv public.invitations%rowtype; begin select * into inv from public.invitations where token_hash=hash for update; if not found or inv.expires_at<=now() or inv.revoked_at is not null then raise exception 'invalid_invitation'; end if; if inv.accepted_by=accepting_user and inv.accepted_at is not null then return inv.group_id; end if; if inv.accepted_at is not null then raise exception 'invalid_invitation'; end if; if inv.created_by=accepting_user then raise exception 'owner_self_invite'; end if; if exists(select 1 from public.group_members where group_id=inv.group_id and user_id=accepting_user and status='active') then return inv.group_id; end if; if (select count(*) from public.group_members where group_id=inv.group_id and status='active')>=2 then raise exception 'group_full'; end if; insert into public.group_members(group_id,user_id,role) values(inv.group_id,accepting_user,'member') on conflict(group_id,user_id) do update set status='active',role='member',left_at=null; update public.invitations set accepted_by=accepting_user,accepted_at=now() where id=inv.id; return inv.group_id; end $$;
revoke all on function private.accept_invite(text,uuid) from public,anon,authenticated;
create function public.accept_invite_service(hash text, accepting_user uuid) returns uuid language sql security definer set search_path='' as $$ select private.accept_invite(hash,accepting_user) $$; revoke all on function public.accept_invite_service(text,uuid) from public,anon,authenticated; grant execute on function public.accept_invite_service(text,uuid) to service_role;
